// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygrmjwvimyszpwolonuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlncm1qd3ZpbXlzenB3b2xvbnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzcyMDcsImV4cCI6MjA2ODM1MzIwN30.f4V7DqlSXaLBEkk8FQ3DTiYNpaLW5WOYQAAtLQJrHS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});